### ISSUE TITLE
Don't remove broken tracks from playlists, highlight instead

### ISSUE THREAD

**Issue by cyancey76** [mxew/firetable-hostbot#7]
If a track is deleted from your YouTube or SC playlist there is no way to go back and find out what was removed. They don't give any notification for you other than "Some tracks were removed."

I really liked that Dubtrack would kind of make a snapshot of the state of your playlist because it would never go back and sync with the original playlist. It made a good resource for re-finding new versions of tracks that had been taken down.

@mxew @chrisrohn I think we should do this as well, by highlighting the broken tracks in a playlist instead of removing them. Then a user has a record of what they need to fix that is more persistent than the @ message you get from Jarvis.

**Comment by cyancey76** [comment]
I thought of another reason to do this. If you play songs that you grabbed from others, Jarvis will remove the broken ones and you'll forget what songs you grabbed.

**Comment by cyancey76** [comment]
@mxew I stand by this suggestion more than ever now.

**Comment by mxew** [comment]
I agree. I’ll work on something ASAP.

**Comment by mxew** [comment]
added in 8fc0e93
